spring.application.name=doctorat-gouv-backend

server.port=8080

# Conf DB PostegreSQL pour le dev
spring.datasource.url=jdbc:postgresql://localhost:5433/doctorat_gouv_db
spring.datasource.username=doctorat_user
spring.datasource.password=motdepassefort
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=WARN
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuration appel API ADUM
# Par d�faut, ex�cute toutes les heures, mais peut �tre personnalis� via la variable d'environnement ADUM_SCHEDULER_CRON
# Scheduler pour l annee N
adum.scheduler.cron=${ADUM_SCHEDULER_CRON:0 0 12 * * *}
# Scheduler pour l annee N-1
adum.scheduler.previous-year.cron=${ADUM_SCHEDULER_PREVIOUS_CRON:0 0 8 * * *}
# Scheduler pour l annee N+1
adum.scheduler.next-year.cron=${ADUM_SCHEDULER_NEXT_CRON:0 0 10 * * *}      
adum.api.username=${ADUM_API_USERNAME}
adum.api.password=${ADUM_API_PASSWORD}
adum.api.base-url=${ADUM_API_BASE_URL:https://www.adum.fr/api/propositionsThese/export.api}
adum.api.year=${ADUM_API_YEAR:2025}
adum.import.rattrapage=${ADUM_IMPORT_RATTRAPAGE:false}


# Configuration appel API Amethis
amethis.api.url=${AMETHIS_API_BASE_URL:https://amethis.doctorat.org/amethis-server/json/prd/gouv}
amethis.import.rattrapage=${AMETHIS_IMPORT_RATTRAPAGE:false}
amethis.scheduler.cron=${AMETHIS_SCHEDULER_CRON:0 */30 * * * *}

# Brevo (ex Sendinblue) configuration
brevo.api.url=${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_MAIL_SENDER}
brevo.sender.name=Doctorat Gouv

app.mail.enabled=false

#albert.api.url=${ALBERT_API_URL:https://api.albert.ai/v1/collections/211775/documents}
albert.base-url=${ALBERT_BASE_URL:https://albert.api.etalab.gouv.fr/v1}
albert.api.key=${ALBERT_API_KEY}
albert.collection.name=doctorat_sujets_dev
albert.collection.id=211775
albert.search.api-limit=100
albert.search.score-threshold=0.3
albert.search.method=hybrid
albert.scheduler.enabled=false
albert.scheduler.cron=${ALBERT_SCHEDULER_CRON:0 0 * * * *}

# Scaleway embedding API
scaleway.api.key=${SCALEWAY_API_KEY}
scaleway.api.url=${SCALEWAY_API_URL:https://api.scaleway.ai/11aa88cb-ec5b-4df9-bcb4-e9e82576ae58/v1/embeddings}
scaleway.model=${SCALEWAY_EMBEDDING_MODEL:bge-multilingual-gemma2}
scaleway.dimensions=${SCALEWAY_EMBEDDING_DIMENSIONS:3584}

# Planification de l'indexation vectorielle (toutes les 2 min en dev)
scaleway.scheduler.cron=${SCALEWAY_SCHEDULER_CRON:0 */2 * * * ?}





