spring.application.name=doctorat-gouv-backend

spring.profiles.active=dev

# Nombre max de résultats retournés par la recherche IA
albert.search.limit=27
# Nombre max de résultats récupérés depuis l'API Albert
albert.search.api-limit=50



