--------------------------------------------------
-- Author: Mohamed Laarbi ELHANI
-- Date: 2024-06-10
-- Description: Script géneral SQL de création du schéma de la base de données pour les propositions de thèses.
-- --------------------------------------------------


-- Script SQL de création de la table proposition_these
CREATE TABLE proposition_these (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    matricule VARCHAR(11) NOT NULL UNIQUE,
    type_proposition VARCHAR(12) NOT NULL,

    date_creation TIMESTAMP,
    date_maj TIMESTAMP,
    date_soumission TIMESTAMP,
    date_mise_en_ligne TIMESTAMP,
    date_limite_candidature TIMESTAMP,
    date_debut_these DATE,

    deposant_orcid VARCHAR(16),
    deposant_nom VARCHAR(50),
    deposant_prenom VARCHAR(25),
    deposant_email VARCHAR(100),

    annee_universitaire VARCHAR(4),
    ecole_doctoral_numero VARCHAR(3),

    unite_recherche_ror VARCHAR(9),
    unite_recherche_libelle VARCHAR(300),
    unite_recherche_code_postal VARCHAR(7),
    unite_recherche_ville VARCHAR(40),

    etablissement_ror VARCHAR(9),
    etablissement_libelle VARCHAR(250),
    etablissement_code_postal VARCHAR(7),
    etablissement_ville VARCHAR(40),

    specialite VARCHAR(255),
    domaine_scientifique VARCHAR(255),

    direction_these_orcid VARCHAR(16),
    direction_these_nom VARCHAR(50),
    direction_these_prenom VARCHAR(25),
    direction_these_email VARCHAR(100),

    codirection_these_orcid VARCHAR(16),
    codirection_these_nom VARCHAR(50),
    codirection_these_prenom VARCHAR(25),
    codirection_these_email VARCHAR(100),

    interdisciplinaire VARCHAR(3),
    cotutelle VARCHAR(3),
    cotutelle_pays_code VARCHAR(3),

    modalites_encadrement TEXT,
    domaines_impact VARCHAR(3),
    objectifs_developpement_durable VARCHAR(3),

    these_titre VARCHAR(255),
    these_titre_anglais VARCHAR(255),

    resume TEXT,
    resume_anglais TEXT,
    thematique_recherche TEXT,
    domaine TEXT,
    objectif TEXT,
    contexte TEXT,
    methode_de_travail TEXT,
    resultats_attendus TEXT,
    references_bibliographiques TEXT,
    conditions_materielles TEXT,
    ouverture_internationale TEXT,
    collaborations_envisagees TEXT,
    valorisation_travaux TEXT,

    confidentiel VARCHAR(3),
    url_infos_complementaires VARCHAR(255),

    financement_etat VARCHAR(255),
    financement_employeur VARCHAR(255),
    financement_origine VARCHAR(255),
    financement_date_debut DATE,
    financement_date_fin DATE,
    financement_details TEXT,

    profil_recherche TEXT,
    profil_recherche_anglais TEXT,

    niveau_anglais_requis VARCHAR(5),
    niveau_francais_requis VARCHAR(5),

    candidature_en_ligne_possible VARCHAR(3)
);


-- Créaation des tables sécondaires pour les listes associées à proposition_these
CREATE TABLE proposition_mots_cles (
    proposition_id BIGINT NOT NULL,
    idx VARCHAR(5),
    mot_cle VARCHAR(255),
    PRIMARY KEY (proposition_id, idx),
    FOREIGN KEY (proposition_id) REFERENCES proposition_these(id)
);

CREATE TABLE proposition_mots_cles_ang (
    proposition_id BIGINT NOT NULL,
    idx VARCHAR(5),
    mot_cle VARCHAR(255),
    PRIMARY KEY (proposition_id, idx),
    FOREIGN KEY (proposition_id) REFERENCES proposition_these(id)
);

CREATE TABLE proposition_domaines_impact (
    proposition_id BIGINT NOT NULL,
    domaine VARCHAR(255),
    FOREIGN KEY (proposition_id) REFERENCES proposition_these(id)
);

CREATE TABLE proposition_objectifs_dd (
    proposition_id BIGINT NOT NULL,
    objectif VARCHAR(255),
    FOREIGN KEY (proposition_id) REFERENCES proposition_these(id)
);

CREATE TABLE proposition_financement_types (
    proposition_id BIGINT NOT NULL,
    type VARCHAR(255),
    FOREIGN KEY (proposition_id) REFERENCES proposition_these(id)
);


